export const UPDATE_AUTH = 'UPDATE_AUTH';
export const LOGOUT = 'LOGOUT';
export const SHOW_LOGIN_MODAL = 'SHOW_LOGIN_MODAL';
export const UPDATE_FAVORITE_MOVIES = 'UPDATE_FAVORITE_MOVIES';
export const UPDATE_MOVIES_WATCHLIST = 'UPDATE_MOVIES_WATCHLIST';
